name: publish
on: [push]
jobs:
  publish-devimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Python devimage
        run: |
          cd ./python
          docker build . -t ghcr.io/mikefarmer01/devimage-python
          docker push ghcr.io/mikefarmer01/devimage-python
